version: '3.9'

services:
  webapp:
    build: .
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - ./storage:/app/storage
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
